osx_image: xcode7

language: objective-c

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool

script:
- xctool clean build test -workspace JSQWebViewController.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

- xctool clean build test -project JSQWebViewController/JSQWebViewController.xcodeproj -scheme JSQWebViewController -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
