osx_image: xcode6.4

language: objective-c

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build test -workspace JSQWebViewController.xcworkspace -scheme Example -sdk iphonesimulator8.4 ONLY_ACTIVE_ARCH=NO
- xcodebuild clean build test -project JSQWebViewController/JSQWebViewController.xcodeproj -scheme JSQWebViewController -sdk iphonesimulator8.4 ONLY_ACTIVE_ARCH=NO
