osx_image: xcode7

language: objective-c

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build test -workspace JSQWebViewController.xcworkspace -scheme Example -sdk iphonesimulator8.3 ONLY_ACTIVE_ARCH=NO
- xcodebuild clean build test -project JSQWebViewController/JSQWebViewController.xcodeproj -scheme JSQWebViewController -sdk iphonesimulator8.3 ONLY_ACTIVE_ARCH=NO
